# Generated by Django 5.1 on 2024-08-20 11:55
import random

from django.db import migrations
from faker import Faker
from datetime import datetime


def populate_models(apps, schema_editor):
    Author = apps.get_model('books_queries', 'Author')
    Book = apps.get_model('books_queries', 'Book')
    BookSale = apps.get_model('books_queries', 'BookSale')
    fake = Faker('ru_RU')

    for _ in range(5):
        Author.objects.create(
            name=fake.name(),
            email=fake.email()
        )

    authors = Author.objects.all()
    for author in authors:
        for _ in range(random.randint(1, 5)):
            Book.objects.create(
                title=fake.text(max_nb_chars=200),
                author=author,
                publication_date=fake.date_between_dates(date_start=datetime(2020, 1, 1), date_end=datetime(2024, 8, 20)),
                price=fake.random_int(min=1, max=100) / 100,
                is_available=fake.random_element(elements=(True, False))
            )

    books = Book.objects.all()
    for book in books:
        if random.randint(1, 5) == 1:
            book.title = 'Python'
            book.save()

        BookSale.objects.create(
            book=book,
            quantity=fake.random_int(min=1, max=100),
            sale_date=fake.date_between_dates(date_start=datetime(2020, 1, 1), date_end=datetime(2024, 8, 20)),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("books_queries", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_models),
    ]
